api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "wood-cart-transform"
type = "function"
uid = "50d16ac1-1e5d-4ae1-a5f6-6079610dd09da47bc02a"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
