name = "WoodSlabs Configurator"
client_id = "b842ae8c8ab502a3bffb591831a716d1"
application_url = "https://woodslabs-api-production.up.railway.app"
embedded = false

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = ["https://woodslabs-api-production.up.railway.app/auth/callback"]

[app_proxy]
url = "https://woodslabs-api-production.up.railway.app"
subpath = "woodslabs"
prefix = "apps"

[webhooks]
api_version = "2026-07"
